name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=1.5.3
  - pytest=7.4.3
  # - scipy=1.5.2
  - scipy >=1.7.1
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
